/* Estación de Contenido — semana de prompts BUUM (originales, sin marcas de terceros).
   Cada prompt es para pegar en ChatGPT SUBIENDO la foto del foco real como referencia.
   Reglas fijas incluidas: foco real, LUZ BLANCA 6500K, marca BUUM, sin marcas ajenas. */
const R = " Usa como referencia la foto del foco LED 60W que subo (cuerpo blanco con facetas de diamante, corona cristalina translúcida arriba, rosca E27 metálica): mantenlo IDÉNTICO y realista. La luz que emite es BLANCA 6500K, nunca cálida/amarilla. Marca BUUM. Sin logos ni marcas de terceros. Alta calidad, foto publicitaria premium.";

const SEMANA = {
 "2026-07-14": { dia:"Martes", piezas:[
   { id:"h_0714", tipo:"historia", hora:"9:00", titulo:"Historia · Foco héroe estilo MINISO",
     obj:"Enganchar en 1 seg · brillo · premium",
     prompts:["Anuncio vertical 9:16 estilo MINISO/Pop Mart: el foco como HÉROE brillando sobre un cubo de acrílico azul translúcido, cielo acuarela azul-blanco, piso reflejante. Composición limpia, muy premium. Espacio arriba para un título corto."+R] },
   { id:"c_0714", tipo:"carrusel", hora:"14:00", titulo:"Carrusel (5) · El foco en cada rincón",
     obj:"Tipo Amazon: mismo foco, 5 contextos reales",
     prompts:[
      "Imagen 1/5, vertical 4:5: el foco encendido en el techo (roseta de cerámica) de una SALA moderna mexicana, iluminando parejo todo el cuarto con luz blanca."+R,
      "Imagen 2/5, vertical 4:5: el mismo foco en una COCINA luminosa, luz blanca que hace ver todo limpio y nítido."+R,
      "Imagen 3/5, vertical 4:5: el mismo foco en un TALLER/garage, luz blanca potente para trabajar."+R,
      "Imagen 4/5, vertical 4:5: el mismo foco en un PATIO exterior de noche, iluminando amplio con luz blanca."+R,
      "Imagen 5/5, vertical 4:5: foto de producto del foco solo, limpio sobre fondo claro, con espacio para poner precio $75."+R] },
   { id:"v_0714", tipo:"video", hora:"19:00", titulo:"Video · Encendido que ilumina el cuarto",
     obj:"Reel corto (se anima con Kling/ffmpeg)",
     prompts:["Imagen base para video vertical 9:16: cuarto en penumbra y el foco a punto de encender; composición para animar un 'encendido' que llena todo de luz BLANCA."+R] },
 ]},
 "2026-07-15": { dia:"Miércoles", piezas:[
   { id:"h_0715", tipo:"historia", hora:"9:00", titulo:"Historia · El gatito presenta el foco",
     obj:"Mascota da personalidad (nuestro 'Dr. Simi')",
     prompts:["Anuncio vertical 9:16, estilo coleccionable Pop Mart: un adorable gatito mascota (personaje propio, NO de ninguna película) presentando con orgullo el foco que brilla con luz blanca, fondo alegre naranja/azul BUUM."+R] },
   { id:"c_0715", tipo:"carrusel", hora:"14:00", titulo:"Carrusel (5) · Por qué el gatito lo recomienda",
     obj:"5 beneficios, uno por tarjeta",
     prompts:[
      "Imagen 1/5 4:5: gatito mascota BUUM señalando el foco encendido — beneficio 'LUZ BLANCA 6500K', fondo azul BUUM."+R,
      "Imagen 2/5 4:5: gatito con cara feliz — beneficio 'ALTA ILUMINACIÓN', el foco muy brillante."+R,
      "Imagen 3/5 4:5: gatito con un relojito — beneficio 'LARGA DURACIÓN'."+R,
      "Imagen 4/5 4:5: gatito con una hojita/ahorro — beneficio 'BAJO CONSUMO'."+R,
      "Imagen 5/5 4:5: gatito junto a la caja del producto — cierre 'CALIDAD BUUM', espacio para precio."+R] },
   { id:"v_0715", tipo:"video", hora:"19:00", titulo:"Video · Gatito enciende la casa",
     obj:"Reel mascota",
     prompts:["Imagen base 9:16: gatito mascota BUUM tocando un interruptor y la casa se llena de luz blanca; composición para animar."+R] },
 ]},
 "2026-07-16": { dia:"Jueves", piezas:[
   { id:"h_0716", tipo:"historia", hora:"9:00", titulo:"Historia · Mayoreo caja de 12",
     obj:"Vender volumen · precio ancla",
     prompts:["Anuncio vertical 9:16 premium: la CAJA de 12 focos BUUM abierta mostrando los focos, con el texto grande 'CAJA DE 12' y espacio para '$899'. Fondo azul BUUM, luz blanca."+R] },
   { id:"c_0716", tipo:"carrusel", hora:"14:00", titulo:"Carrusel (5) · Conviene comprar caja",
     obj:"Ahorro por mayoreo",
     prompts:[
      "Imagen 1/5 4:5: la caja de 12 focos BUUM, hero, fondo azul."+R,
      "Imagen 2/5 4:5: comparación visual '1 pieza $99 vs caja de 12 $75 c/u' (deja lugar para los números)."+R,
      "Imagen 3/5 4:5: varios focos idénticos alineados mostrando abundancia/stock."+R,
      "Imagen 4/5 4:5: foco encendido, énfasis en luz blanca y calidad."+R,
      "Imagen 5/5 4:5: llamado a la acción 'COMPRA AL MAYOREO', espacio para texto."+R] },
   { id:"v_0716", tipo:"video", hora:"19:00", titulo:"Video · Caja que se llena de focos",
     obj:"Reel mayoreo",
     prompts:["Imagen base 9:16: caja BUUM y focos alrededor, composición para animar 'la caja se llena'."+R] },
 ]},
 "2026-07-17": { dia:"Viernes", piezas:[
   { id:"h_0717", tipo:"historia", hora:"9:00", titulo:"Historia · Brillo que se nota",
     obj:"Mostrar potencia real",
     prompts:["Anuncio vertical 9:16: un cuarto iluminado de forma pareja y brillante por el foco (luz blanca), sensación 'wow, cómo alumbra'. Premium, limpio."+R] },
   { id:"c_0717", tipo:"carrusel", hora:"14:00", titulo:"Carrusel (5) · Tour por la casa iluminada",
     obj:"Recorrido de cuartos",
     prompts:[
      "Imagen 1/5 4:5: recámara iluminada con luz blanca del foco."+R,
      "Imagen 2/5 4:5: cocina iluminada, todo nítido."+R,
      "Imagen 3/5 4:5: baño/pasillo bien iluminado."+R,
      "Imagen 4/5 4:5: patio de noche iluminado amplio."+R,
      "Imagen 5/5 4:5: foco de producto + espacio para precio $75."+R] },
   { id:"v_0717", tipo:"video", hora:"19:00", titulo:"Video · Recorrido iluminado",
     obj:"Reel tour",
     prompts:["Imagen base 9:16: casa vista bonita para animar un recorrido cuarto por cuarto con luz blanca."+R] },
 ]},
 "2026-07-18": { dia:"Sábado", piezas:[
   { id:"h_0718", tipo:"historia", hora:"10:00", titulo:"Historia · Fin de semana acogedor",
     obj:"Lifestyle · aspiracional",
     prompts:["Anuncio vertical 9:16 lifestyle: sala cálida y acogedora pero iluminada con LUZ BLANCA nítida del foco (el ambiente puede ser cozy, pero la luz se lee blanca). Premium DTC."+R] },
   { id:"c_0718", tipo:"carrusel", hora:"14:00", titulo:"Carrusel (5) · Detalles del producto",
     obj:"Macro y calidad",
     prompts:[
      "Imagen 1/5 4:5: macro de las facetas de diamante del foco, calidad premium."+R,
      "Imagen 2/5 4:5: macro de la rosca E27 metálica."+R,
      "Imagen 3/5 4:5: la corona cristalina translúcida iluminada."+R,
      "Imagen 4/5 4:5: foco completo de 3/4, elegante."+R,
      "Imagen 5/5 4:5: foco + espacio para specs (60W, luz blanca)."+R] },
   { id:"v_0718", tipo:"video", hora:"19:00", titulo:"Video · Giro 360 del foco",
     obj:"Reel producto",
     prompts:["Imagen base 9:16: foco centrado sobre fondo limpio para animar un giro 360."+R] },
 ]},
 "2026-07-19": { dia:"Domingo", piezas:[
   { id:"h_0719", tipo:"historia", hora:"11:00", titulo:"Historia · Tipográfica potente",
     obj:"Mensaje audaz de marca",
     prompts:["Anuncio vertical 9:16 tipográfico audaz: fondo azul BUUM, el foco a un lado brillando (luz blanca), y espacio grande para un titular tipo 'ILUMINA TU MUNDO'. Estilo bold, moderno."+R] },
   { id:"c_0719", tipo:"carrusel", hora:"14:00", titulo:"Carrusel (5) · Frases + foco",
     obj:"5 mensajes de marca",
     prompts:[
      "Imagen 1/5 4:5: foco brillando, espacio para frase 'Súper calidad y súper precio'."+R,
      "Imagen 2/5 4:5: foco, espacio para 'Vale la pena'."+R,
      "Imagen 3/5 4:5: foco, espacio para 'Luz blanca que hace la diferencia'."+R,
      "Imagen 4/5 4:5: foco, espacio para 'Ilumina de más'."+R,
      "Imagen 5/5 4:5: cierre de marca BUUM + precio."+R] },
   { id:"v_0719", tipo:"video", hora:"19:00", titulo:"Video · Frases animadas",
     obj:"Reel tipográfico",
     prompts:["Imagen base 9:16: foco a un lado sobre fondo azul, dejando área para texto animado."+R] },
 ]},
 "2026-07-20": { dia:"Lunes", piezas:[
   { id:"h_0720", tipo:"historia", hora:"9:00", titulo:"Historia · Arranca la semana con luz",
     obj:"Motivacional lunes",
     prompts:["Anuncio vertical 9:16: mañana luminosa, el foco encendido con luz blanca dando energía de 'nuevo comienzo'. Fresco, premium."+R] },
   { id:"c_0720", tipo:"carrusel", hora:"14:00", titulo:"Carrusel (5) · Guía rápida del foco",
     obj:"Educativo simple",
     prompts:[
      "Imagen 1/5 4:5: '¿Qué es?' foco 60W de alta potencia, hero."+R,
      "Imagen 2/5 4:5: '¿Dónde va?' foco en roseta de techo."+R,
      "Imagen 3/5 4:5: '¿Cuánto ilumina?' cuarto muy iluminado."+R,
      "Imagen 4/5 4:5: '¿Cuánto cuesta?' foco + espacio $75 / caja $899."+R,
      "Imagen 5/5 4:5: '¿Dónde comprar?' cierre BUUM."+R] },
   { id:"v_0720", tipo:"video", hora:"19:00", titulo:"Video · Buenos días BUUM",
     obj:"Reel motivacional",
     prompts:["Imagen base 9:16: escena de mañana con el foco encendido, para animar."+R] },
 ]},
};
